version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: weather
    networks:
      - spring-network
    volumes:
      - mysql-data:/var/lib/mysql  # Optional for data persistence

  springboot-mysql-docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: mysql-db  # Use service name
      MYSQL_PASSWORD: 0000
      MYSQL_PORT: 3306
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  mysql-data:  # Optional for data persistence
